version: '3'

services:
  my-app:
    build: .
    container_name: my-app-container
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    command: npm run dev
    environment:
      SERVICE: shopper
      SERVER_PORT: 8081
      DATABASE_URL: localhost
      DATABASE_PORT: 3306
      DATABASE_USER: teste
      DATABASE_PASSWORD: teste
      DATABASE: local_database
