version: '3'

services:
  my-app:
    build: .
    container_name: my-app-container
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    command: npm run dev
    environment:
      SERVICE: shopper
      SERVER_PORT: 8081
      DATABASE_URL: mysql-container
      DATABASE_PORT: 3306
      DATABASE_USER: teste
      DATABASE_PASSWORD: teste
      DATABASE: local_database
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: local_database
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
